### ISSUE TITLE
Riguarda e controlla.

### ISSUE THREAD

**Issue by MacPapo** [MacPapo/UniManual#5]
Master mi serve una mano a controllare e a snellire basi di dati, visto che ho usato il supporto del libro è venuto troppo verboso, vorrei che guardassi cosa tenere e cosa no, mi raccomando quello che bisogna tenere deve essere nelle slide, quello che non c'è controlla che magari non sia interessante!! Tutto quello che è ora presente è corretto quindi non modificare quello che c'è scritto, se vuoi puoi riassumere delle parti. Grazie!

**Comment by mastrodeimastri** [comment]
Jack, la review è terminata e il tutto è stato committato
