### ISSUE TITLE
Vai avanti con UniManual

### ISSUE THREAD

**Issue by MacPapo** [MacPapo/UniManual#6]
Mastro siccome sta sera sei libero dalle 20 in poi, non scomodarti a raggiungerci, vai pure avanti con UniManual, in un corso a tua scelta che c'è l'imbarazzo della scelta.
Grazie e buon lavoro!

Con amore da @MacPapo & @Visco01

**Comment by mastrodeimastri** [comment]
Se ho voglia vado avanti se no farò un altra volta.
Buona competizione ;)
