### ISSUE TITLE
Add in .gitignore ltximg directory

### ISSUE THREAD

**Issue by MacPapo** [MacPapo/UniManual#8]
In .org files thanks to the new "#+startup: latexpreview" Emacs create a directory called  ltximg  in the root of the current directory, I need help to fix that in the .gitignore, because I don't want to push all the ltximg directories. Thanks.

**Comment by Visco01** [comment]
Fixare gitignore cosa??

**Comment by MacPapo** [comment]
LEGGI IL NOME DELL'ISSUE

**Comment by Visco01** [comment]
BASTA FARE UNA PULLATA!! Cosa serve aprire un issue per questo

**Comment by Visco01** [comment]
🥴🥴🥴🥴

**Comment by Visco01** [comment]
🥴🥴🥴🥴

**Comment by Visco01** [comment]
[This](https://github.com/MacPapo/UniManual/commit/f789f3505df6b9e1f1d42bea9eb39d95a1803c15) should have fixed it. Before pulling it, make sure you have all your ltximg images discarded.
