### ISSUE TITLE
PES probab.org enhancement

### ISSUE THREAD

**Issue by Visco01** [MacPapo/UniManual#9]
It would be nice to **add a description to each formula** in [probab.org](https://github.com/MacPapo/UniManual/blob/master/src/pes/mod1/probab.org), since it appears to be a shopping list right now.
 This change should be useful in the future: in the coming months it will help us to **remember better** these formulas.
Thanks!

**Comment by mastrodeimastri** [comment]
No problem, I've to refactor all yes files so I'll do that
